# Generated by Django 4.2.1 on 2023-07-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='home',
            name='house',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='home',
            name='street',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
