# Generated by Django 4.2.1 on 2023-07-20 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_home_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='date',
            new_name='data',
        ),
    ]
