# Generated by Django 4.2.1 on 2023-07-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_date_home_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
