# Generated by Django 4.2.1 on 2023-07-20 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_home_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='data',
        ),
    ]
