# Generated by Django 4.2.1 on 2023-07-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_home_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='num',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='home',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
