# Generated by Django 4.2.1 on 2023-07-28 03:16

from django.db import migrations


def set_home(core, schema_editor):
    Home = core.get_model('core', 'Home')
    db_alias = schema_editor.connection.alias
    Home.objects.using(db_alias).create(street='data_test_street', house='data_test_house', city='data_test_city',
                                        num='data_test_num')


def reverse_home(core, schema_editor):
    Home = core.get_model('core', 'Home')
    db_alias = schema_editor.connection.alias
    Home.objects.using(db_alias).filter(street='data_test_street', house='data_test_house', city='data_test_city',
                                        num='data_test_num').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_squashed_0014_school_num'),
    ]

    operations = [
        migrations.RunPython(set_home, reverse_home),
    ]
