# Generated by Django 4.2.1 on 2023-08-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230728_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
